CREATE TABLE IF NOT EXISTS brands (
    BrandID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BrandName VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS brandType (
    TypeID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TypeName VARCHAR(100) NOT NULL
);

ALTER TABLE brand
    ADD FOREIGN KEY (TypeID_FK) REFERENCES brandType(TypeID);